version: '3.8'

services:
  # O Banco de Dados
  postgres:
    image: postgres:15
    container_name: makeup-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 # <--- Coloque a senha do seu application.properties
      POSTGRES_DB: makeup_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # O Cache
  redis:
    image: redis:alpine
    container_name: makeup-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data: